spring.h2.console.enabled: true
spring:
  servlet:
    multipart:
      max-file-size: 10MB  # ?? ??? ? ??? ?? ?? ??
      max-request-size: 20MB  # ?? ? ?? ? ?? ? ?? ??
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.type: trace